name: Node.js CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: codebuild-4ears-me-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: npm run prettier:check --if-present
      - run: npm test
      - run: npm run build --if-present
